export const CATEGORIES = [
    "Audio",
    "Beauty & Personal Care",
    "Car Accessories",
    "Computers & Tech",
    "Education",
    "Food & Drinks",
    "Furniture",
    "Health & Nutrition",
    "Hobbies & Toys",
    "Luxury",
    "Men's fashion",
    "Phones & Gadgets",
    "Photography",
    "Sports",
    "Tools",
    "Home Appliances",
    "Video Games",
    "Women's fashion",
    "Others"
];
export const IDS = {
    AUDIO: 0,
    BEAUTY: 1,
    CAR: 2,
    COMPUTER: 3,
    EDUCATION: 4,
    FOOD: 5,
    FURNITURE: 6,
    HEALTH: 7,
    HOBBIES: 8,
    LUXURY: 9,
    MEN_FASHION: 10,
    PHONES: 11,
    PHOTOG: 12,
    SPORTS: 13,
    TOOLS: 14,
    APPLIANCES: 15,
    GAMES: 16,
    WOMEN_FASHION: 17,
    OTHERS: 18
}